spring.application.name=Bastion

spring.datasource.url=jdbc:postgresql://localhost:5432/Bastion
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your_base_64_ecoded_secret_key
jwt.expiry.hours=24

